### PR TITLE
refactor attribute conversion to make it more approachable for newcomers

### PR DESCRIPTION
**Pull request by kybishop**
1. Adds comments explaining what things do
2. Removes deep conditional nesting in favor of early returns (less context == more better)
3. Pulls out a few logical block into their own methods (better encapsulation)
4. A few bike shedding changes, like newlines before control flow statements and alphabetized variables.

### CODE REVIEW

**Comment by kybishop** [comment]
I have tested this on my own app without issue

**Comment by RobbieTheWagner** [comment]
@kybishop this looks fine to me, however, I am curious, could we use an ES6 class here instead of all the prototype stuff? I know it's probably like it is to have compatibility with like node 0.12, but I think 2.0 would be a perfect time to drop support for old node too.

**Comment by kybishop** [comment]
@rwwagner90 agreed! 0.12 is past EOL anyways.

Pushed a commit to es6-ify the file with es6 features available to the oldest active node LTS, 4.x.

**Comment by RobbieTheWagner** [comment]
@kybishop looks like the builds are failing. I think we need `"use strict";` I am seeing this `Block-scoped declarations (let, const, function, class) not yet supported outside strict mode`

The class looks good though! All the code work locally for you with the ES6 stuff?

**Comment by kybishop** [comment]
Strange that it worked on my machine without `"use strict"`, all good on Travis now.

**Pull request merged**
